### ISSUE TITLE
BUG: Pip install failures on windows.

### ISSUE THREAD

**Issue by scott-huberty** [lina-usc/pylossless#118]
Our pip install method fails On windows.
has to do with this line in `setup.py`:

https://github.com/lina-usc/pylossless/blob/ba3e26323a8e10d3f91994b9a7a39d9bb36ebab6/setup.py#L29

Maybe we can include a fix in #117

**Comment by christian-oreilly** [comment]
A full error message would be useful. Without it I cannot comment.

**Comment by Andesha** [comment]
just to be clear - it's like due to the path formatting with the wrong slashes...

**Comment by scott-huberty** [comment]
It was an `encoding` error in `read_text()`. Maybe it can be fixed by explicitly specifying what encoding to use but honestly I have not tried to fix it yet!

**Comment by christian-oreilly** [comment]
@scott-huberty The CI passes with Windows. Should I conclude that this issue was resolved in some PR or is it that this specific issue was not covered by the CI?

**Comment by scott-huberty** [comment]
Ah yes.. This was closed by #169 !!!!
