### ISSUE TITLE
Make the LosslessPipeline constructor more user-friendly

### ISSUE THREAD

**Issue by christian-oreilly** [lina-usc/pylossless#123]
The constructor of LosslessPipeline should accept a a `config` argument that can be a string/Path object (pointing to a config file) or a Config object directly.

**Comment by scott-huberty** [comment]
+1!

**Comment by christian-oreilly** [comment]
Nevermind. Now I remember why it is tedious not to be able to pass a Config object directly. That was the intent for this issue...
