### ISSUE TITLE
enhancement: make a nice __repr__ for pipeline class

### ISSUE THREAD

**Issue by scott-huberty** [lina-usc/pylossless#128]
Note for self: make a nice `__repr__` for pipeline class and each `flags` class.

**Comment by christian-oreilly** [comment]
You may also want to reimplement the jupyter notebooks specific repr functions (e.g., the one for HTML) to make it even nicer when used in a notebook: https://ipython.readthedocs.io/en/stable/config/integrating.html#custom-methods

**Comment by scott-huberty** [comment]
That's a good idea. A nice HTML for the pipeline class, and just simple `_repr_` for the flag classes.

**Comment by scott-huberty** [comment]
Closed by #146
