### ISSUE TITLE
Release .2

### ISSUE THREAD

**Issue by scott-huberty** [lina-usc/pylossless#165]
There have been a number of bug fixes and enhancements since the initial release, so I think now is a good time to cut a new release. ~~I've started a [project tracker](https://github.com/orgs/lina-usc/projects/3/views/1)~~. I'm thinking September 1st is a generous timeline. I'm also going to be processing some data in August and so I will take the opportunity to look out for anything that should be improved. @christian-oreilly does this sound reasonable to you?

EDIT: I forgot, we already have a [project tracker for .2.](https://github.com/lina-usc/pylossless/milestone/2) I deleted the new one that I created.

**Comment by christian-oreilly** [comment]
Sure. Not all open issues are associated with a release. Maybe we should go through those that are not associated and attach them to a tentative release? It can be .3 or later if you don't want to include them in .2... and we can adjust these down the road... but having them labeled may help provide clarity about the objectives of the forthcoming releases.

**Comment by scott-huberty** [comment]
Sure! I recently assigned some to .3, but feel free to swap tickets between .3 and .2 as you see fit.

**Comment by christian-oreilly** [comment]
@scott-huberty `StLaurent`'s fine for the 0.2 release name?

**Comment by scott-huberty** [comment]
sure :)

Question: If-when we release minor/patch releases do we just fall back to SemVer for the name of those releases (e.g 0.2.1)?

**Comment by christian-oreilly** [comment]
> Question: If-when we ship minor/patch releases do we just fall back to SemVer for the name of those releases (e.g 0.2.1)?

Seems reasonable to me!

**Comment by christian-oreilly** [comment]
PyLossless v0.2.0 released and deployed on PYPI! 🎆

**Comment by scott-huberty** [comment]
Woohoo!!!
