### ISSUE TITLE
BUG: we broke the pipeline

### ISSUE THREAD

**Issue by scott-huberty** [lina-usc/pylossless#38]
Latest commit (f9a2e2f) broke the pipeline. 

Hopefully just an indentation error. I am going to try to push a PR today.

**Comment by christian-oreilly** [comment]
That can be closed? FYI, if you had use "This should fix #38" instead of "solve", I think the merge would have closed that issue automatically.

**Comment by scott-huberty** [comment]
Yeah -- I was wondering why git wasn't automatically closing the issues!

closing.
