### ISSUE TITLE
BUG: ica files not saving with '_Ica" suffix in derivatives folder

### ISSUE THREAD

**Issue by scott-huberty** [lina-usc/pylossless#41]
Given line 1231, it looks like the ICA files should save with the suffix '_ica' but they are not (I just tested saving the pipeline on my local machine).  

https://github.com/lina-usc/pylossless/blob/f9a2e2f443425b2c21d5110f178692a5d76c0383/pylossless/pipeline.py#L1223-L1255

Until we fix this, the QCR dashboard will return an error when trying to load the ICA

**Comment by christian-oreilly** [comment]
Well, first, the comments in that block are off (it is loading, not saving... they are obviously from a copy-and-past from the corresponding function).

**Comment by christian-oreilly** [comment]
This line:
https://github.com/lina-usc/pylossless/blob/f9a2e2f443425b2c21d5110f178692a5d76c0383/pylossless/pipeline.py#L1089
should have a `+ "_ica"` to fix this issue.

**Comment by scott-huberty** [comment]
Yup -that confused me because wasn't even the block in question. The fix needed to be here:

https://github.com/lina-usc/pylossless/blob/f9a2e2f443425b2c21d5110f178692a5d76c0383/pylossless/pipeline.py#L1066-L1091

**Comment by scott-huberty** [comment]
> This line:
> 
> https://github.com/lina-usc/pylossless/blob/f9a2e2f443425b2c21d5110f178692a5d76c0383/pylossless/pipeline.py#L1089
> 
> 
> should have a `+ "_ica"` to fix this issue.

See my PR

**Comment by scott-huberty** [comment]
> Well, first, the comments in that block are off (it is loading, not saving... they are obviously from a copy-and-past from the corresponding function).

Can you request a change in your PR review to change that?

**Comment by christian-oreilly** [comment]
Yeah, I saw this after. You change is good.

**Comment by christian-oreilly** [comment]
> > Well, first, the comments in that block are off (it is loading, not saving... they are obviously from a copy-and-past from the corresponding function).
> 
> Can you request a change in your PR review to change that?

Just made the edits on PR #42
