### ISSUE TITLE
Enforce flake8, codespell, pydocstyle in pylossless.dash module

### ISSUE THREAD

**Issue by scott-huberty** [lina-usc/pylossless#66]
Next up on our journey towards PEP8 / Numpydoc compliance.

These ones might be a doozy.

**Comment by Andesha** [comment]
I'll likely get to this soon, so don't start it yourself :wink:

**Comment by scott-huberty** [comment]
Have fun!!!! 😉

**Comment by Andesha** [comment]
What's the codespell thing you use?

**Comment by Andesha** [comment]
thanks!

**Comment by scott-huberty** [comment]
@Andesha let me know if you want me to merge #62 now or after your done.

There is a decent chance that there will be some conflicts that need to be resolved if you've already started the linting work. 

I am fine with handling conflicts in #62 if needed.

**Comment by scott-huberty** [comment]
Ok i'll wait to merge it until we have your PR merged.

> "too many instance variables"

interesting... never heard of this one.

**Comment by scott-huberty** [comment]
@Andesha what linter are you using?

**Comment by Andesha** [comment]
Odd... now that you mention it I was trying to use flake8... :thinking:

**Comment by Andesha** [comment]
good thing you noticed that - I had conflicting linting tools going and it was causing huge issues...

its been fixed now and is also showing way less problems so I should be done shortly(-ish)

**Comment by Andesha** [comment]
can prolly close this now due to #76
