### ISSUE TITLE
Concatenate Overlapping `mne.annotations`

### ISSUE THREAD

**Issue by scott-huberty** [lina-usc/pylossless#75]
In cases where there are multiple subsequent `Epochs` that are all annotated with the same pylossless flag (i.e. `flag_ch_sd_epoch`),  or where there is a small gap annotation (i.e. `flag_ch_sd_epoch` - `gap` -  `flag_ch_sd_epoch` ), I think we can concatenate these annotations to be a single annotation. 

![image](https://user-images.githubusercontent.com/52462026/228025181-7a06326d-41ac-4dab-8309-1b66bcac8f14.png)

This will make adjusting these annotations in the `qcr` dashboard easier, and makes reading the annotation labels easier.

This shouldn't be too hard. Probably similar to the code we wrote for overlapping eyetracking annotations in MNE.

**Comment by christian-oreilly** [comment]
Sounds reasonable to me...
