### ISSUE TITLE
Topomap refactoring

### ISSUE THREAD

**Issue by christian-oreilly** [lina-usc/pylossless#90]
The objective of this issue is to refactor the topomap code so that the generation of a single topomap is a function or class of its own, so that it can be more easily reused outside the specific context of PyLossless (for an eventual fork of the visual components to their own project).

**Comment by scott-huberty** [comment]
> The objective of this issue is to refactor the topomap code so that the generation of a single topomap is a function or class of its own, so that it can be more easily reused outside the specific context of PyLossless (for an eventual fork of the visual components to their own project).

I've had this on my ind as well.. +1!

**Comment by christian-oreilly** [comment]
Yeah... that was self-interested. I want to make a topoplot now for some project and instead of going the usual way of tweaking mne code to get it done, I thought I give this a shot.

**Comment by scott-huberty** [comment]
Well.. If you end up getting to it on your own - let me know if any of the topo Docstring is incorrect/confusing - I did my best to represent the code but i'm sure I made mistakes.

**Comment by scott-huberty** [comment]
> that was self-interested. I want to make a topoplot now for some project and instead of going the usual way of tweaking mne code to get it done, I thought I give this a shot.

Nah IMO this is a perfect example of how a feature request should be done.. Driven by a real and reasonable use-case!

**Comment by christian-oreilly** [comment]
That thing is mostly done. Took much more time that I cared for, but it is done. For plotting a single topomap:

<img width="819" alt="image" src="https://user-images.githubusercontent.com/5932954/230802013-3147b32f-8e17-4bd1-b02a-0ab2945f2ba9.png">

For a grid of topomaps:

<img width="540" alt="image" src="https://user-images.githubusercontent.com/5932954/230802042-68c3ced3-7a50-48b2-b035-9520b930fc9c.png">

For embedding it as a dash component of an existing app:

<img width="655" alt="image" src="https://user-images.githubusercontent.com/5932954/230802076-064ad350-dbda-44df-a417-ef4f2e767aa4.png">

For an on-the-fly standalone dash app:

<img width="702" alt="image" src="https://user-images.githubusercontent.com/5932954/230802113-52ca29d6-b4f0-4e0b-a78b-a9ac0df3f59b.png">

These classes are properly integrated, such that you can get a plotly figure from the dash objects:

<img width="421" alt="image" src="https://user-images.githubusercontent.com/5932954/230802147-5be4e948-2799-4f3e-93ef-e862f758a471.png">

@scott-huberty We should discuss package naming because I think it would be a good occasion to push this into a new repo in the context of #94 (which will also support #33).

**Comment by scott-huberty** [comment]
Looks awesome! 

Yes, let's chat this week
