### ISSUE TITLE
Re-referencing is causing weird signal properties?

### ISSUE THREAD

**Issue by scott-huberty** [lina-usc/pylossless#96]
I _assume_ this is only relevant to my development branch where we moved `flag_outlier_chs` into `rereference` (but I can confirm when I switch to the main branch.

BEFORE running the pipeline:

![image](https://user-images.githubusercontent.com/52462026/231212278-b4810806-aa28-44e6-8c7f-69def04b3ccc.png)

Looks good.

AFTER running `flag_ch_sd_ch` (the first step of the pipeline. The recording is re-referenced 2 times by the end of this step FYI...)

![image](https://user-images.githubusercontent.com/52462026/231212784-8e5321bf-5f5c-4998-a05d-57f9189496fc.png)

the signals are not legible.

**Comment by scott-huberty** [comment]
The trick seems to be to do a `pick_types(eeg=True)` here:

https://github.com/lina-usc/pylossless/blob/2095f13eff76c5abd7729340642b57424511a207/pylossless/pipeline.py#L81-L83

![image](https://user-images.githubusercontent.com/52462026/231218947-50792776-edc8-40a7-945e-84f68bd567cf.png)

Which blows my mind a little.. I'd assume that by default MNE wouldn't let a non-data channel (i.e. STIM channel) be a reference!

**Comment by christian-oreilly** [comment]
> Which blows my mind a little.. I'd assume that by default MNE wouldn't let a non-data channel (i.e. STIM channel) be a reference!

I think it probably does use only EEG channels by default but that it assumes that we know what we are doing so if we give it explicitly a list of channels, it uses that list without doing further exclusion... and I suspect that we were explicitly passing this stim channel to the rereferencing function:
```python
        inst.set_eeg_reference(ref_channels=[ch for ch in inst.ch_names
                                             if ch not in self['manual']],
                               **kwargs)
```
